spring:
  application:
    name: stp
  profiles:
    active: ${PROFILE_RUN:dev}
  datasource:
    url: jdbc:postgresql://localhost:5432/stpdb
    driverClassName: org.postgresql.Driver
    username: ${USERDB:admin}
    password: ${PASSWORDDB:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update #create-drop
    show-sql: true
server:
  port: ${SERV_PORT:3004}


