name: Deploy to aws

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Maven
      working-directory: projeto-spring-api
      run: mvn clean package -DskipTests=true

    - name: Upload app
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: projeto-spring-api/target/*.jar
    
    - name: Upload conf
      uses: actions/upload-artifact@v3
      with:
        name: java-conf
        path: projeto-spring-api/src/main/resources/application.prod.properties

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download app
      uses: actions/download-artifact@v3
      with:
        name: java-app
        path: .

    - name: Download conf
      uses: actions/download-artifact@v3
      with:
        name: java-conf
        path: .
    
    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
        EC2_HOST_PORT: ${{ secrets.EC2_HOST_PORT }}
      run: |
        echo "${{ secrets.EC2_KEY }}" > ec2-key.pem
        chmod 400 ec2-key.pem
        scp -o StrictHostKeyChecking=no -P ${{ secrets.EC2_HOST_PORT }} -i ec2-key.pem target/*.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/produto-api.jar
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.EC2_HOST_PORT }} -i ec2-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          pkill -f 'java -jar' || true
          nohup java -Dspring.config.additional-location=application.prod.properties -jar /home/${{ secrets.EC2_USER }}/produto-api.jar > app.log 2>&1 &
        EOF
      #continue-on-error: true